name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Local Build
      run: clj -X:nextjournal/clerk
    - name: Garden build
      run: curl https://github.clerk.garden/emlyn/advent-of-clerk?update=1

